// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Welcome(loggedin bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex flex-col justify-center items-center min-h-screen gap-8\"><h1 class=\"text-2xl text-blue-600 mt-3\">DOMAIN EXPANSION</h1><h2 class=\"text-3xl text-blue-800 mt-3\">INFINIT VOID</h2><div class=\"mt-12 flex justify-center gap-8\"><a href=\"/posts\" class=\"btn btn-lg btn-link btn-primary\">view posts</a> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if loggedin {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<a href=\"/account\" class=\"btn btn-lg btn-link btn-accent\">account</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<a href=\"/sign\" class=\"btn btn-lg btn-link btn-secondary\">login / sign up</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><button class=\"btn btn-outline btn-primary\" hx-post=\"alpinetest\" hx-target=\"#res\">test alpine</button><div id=\"res\"></div><div class=\"flex justify-center gap-16\"><div x-data=\"{colab1:0}\" class=\"flex flex-col justify-center items-center gap-3\"><button hx-post=\"/colab1\" hx-swap=\"none\" :hx-vals=\"() => ({message:colab1})\" x-on:htmx:after-request=\"colab1 = $event.detail.xhr.responseText\" class=\"btn btn-primary\">test colab 1</button><p x-text=\"colab1\"></p></div><div x-data=\"{colab1:0}\" class=\"flex flex-col justify-center items-center gap-3\"><button hx-post=\"/colab1\" hx-swap=\"none\" :hx-vals=\"JSON.stringify({message:colab1})\" x-on:htmx:after-request=\"colab1 = $event.detail.xhr.responseText\" class=\"btn btn-secondary\">test colab 2</button><p x-text=\"colab1\"></p></div><div x-data=\"{colab2:0, crow:true}\" class=\"flex flex-col justify-center items-center gap-3\"><button @click=\"crow = false; \n                fetch('/apitest', {\n                method: 'POST',\n                headers: {'Content-Type': 'application/json', 'X-Csrf-Token': document.cookie.split('; ').find(r => r.startsWith('csrf_='))?.split('=')[1]},\n                body: JSON.stringify({message:colab2})\n                }).then(r=>r.json()).then(v => {colab2 = v; crow = true})\" class=\"btn btn-accent\">test api fetch</button><p x-text=\"colab2\" :class=\"crow? 'text-green-600' : 'text-red-700'\"></p></div><div x-data=\"{colab2:0, crow:true}\" class=\"flex flex-col justify-center items-center gap-3\"><button hx-post=\"/apitest\" hx-swap=\"none\" hx-ext=\"json-enc\" :hx-vals=\"JSON.stringify({message:colab2})\" x-on:htmx:after-request=\"colab2 = JSON.parse($event.detail.xhr.responseText).message; crow= !crow\" class=\"btn btn-accent\">this shit does not work</button><p x-text=\"colab2\" :class=\"crow? 'text-green-600' : 'text-red-700'\"></p></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
